const timer_vars = {
  TIMER_START: "TIMER_START",
  TIMER_STOP: "TIMER_STOP",
  TIMER_RESET: "TIMER_RESET",
  TIMER_FROM_LOCAL_STORAGE: "TIMER_FROM_LOCAL_STORAGE",
  TIMER_UPDATE: "TIMER_UPDATE",
}
export default timer_vars;
